apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: celery-question-generator-ai-worker-pdb
  labels:
    app: celery-question-generator-ai-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: celery-question-generator-ai-worker

