apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: celery-bulk-upload-worker-pdb
  labels:
    app: celery-bulk-upload-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: celery-bulk-upload-worker

