apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: celery-enrichment-worker-pdb
  labels:
    app: celery-enrichment-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: celery-enrichment-worker

