apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: examxv2-production

resources:
  - ../../base
  - storage/pv.yaml
  - storage/pvc.yaml
  - storage/storage-class.yaml

labels:
  - pairs:
      environment: production
      tier: prod
    includeSelectors: false

patches:
  # Backend Deployment patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: examxv2-backend
      spec:
        replicas: 2
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: examxv2-backend
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-20250824-105825-d1747844670a77f055bdfcfd9030376717c510e4"
              resources:
                requests:
                  cpu: "4"
                  memory: "10Gi"
                limits:
                  cpu: "6"
                  memory: "20Gi"
              env:
              - name: WORKERS
                value: "6"
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: examxv2-backend

  # Celery Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-worker-default
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: celery-worker-default
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-20250824-105825-d1747844670a77f055bdfcfd9030376717c510e4"
              resources:
                requests:
                  cpu: "2"
                  memory: "10Gi"
                limits:
                  cpu: "4"
                  memory: "20Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: celery-worker-default
  
  # Celery Bulk Upload Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-bulk-upload-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: celery-bulk-upload-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-20250824-105825-d1747844670a77f055bdfcfd9030376717c510e4"
              resources:
                requests:
                  cpu: "2"
                  memory: "10Gi"
                limits:
                  cpu: "4"
                  memory: "20Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: celery-bulk-upload-worker

  # Celery Enrichment Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-enrichment-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: celery-enrichment-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-20250824-105825-d1747844670a77f055bdfcfd9030376717c510e4"
              resources:
                requests:
                  cpu: "2"
                  memory: "10Gi"
                limits:
                  cpu: "4"
                  memory: "20Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: celery-enrichment-worker

  # Celery Question Generator AI Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-question-generator-ai-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: celery-question-generator-ai-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-20250824-105825-d1747844670a77f055bdfcfd9030376717c510e4"
              resources:
                requests:
                  cpu: "2"
                  memory: "10Gi"
                limits:
                  cpu: "4"
                  memory: "20Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: celery-question-generator-ai-worker
  # Celery beat patches
  # - patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: celery-beat
  #     spec:
  #       replicas: 1
  #       template:
  #         spec:
  #           serviceAccountName: examxv2-production-sa
  #           containers:
  #           - name: celery-beat
  #             resources:
  #               requests:
  #                 cpu: "1"
  #                 memory: "10Gi"
  #               limits:
  #                 cpu: "2"
  #                 memory: "20Gi"
  #   target:
  #     kind: Deployment
  #     name: celery-beat

  # Celery Flower patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-flower
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: flower
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-20250824-105825-d1747844670a77f055bdfcfd9030376717c510e4"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
    target:
      kind: Deployment
      name: celery-flower
  # Backend Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: examxv2-backend-pod-autoscaler
      spec:
        minReplicas: 2
    target:
      kind: HorizontalPodAutoscaler
      name: examxv2-backend-pod-autoscaler

  # Celery Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-worker-default-autoscaler
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-worker-default
    target:
      kind: HorizontalPodAutoscaler
      name: celery-worker-default-autoscaler

  # Celery Bulk Upload Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-bulk-upload-worker-autoscaler
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-bulk-upload-worker
    target:
      kind: HorizontalPodAutoscaler
      name: celery-bulk-upload-worker-autoscaler

  # Celery Enrichment Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-enrichment-worker-autoscaler
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-enrichment-worker
    target:
      kind: HorizontalPodAutoscaler
      name: celery-enrichment-worker-autoscaler

  # Celery Question Generator AI Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-question-generator-ai-worker-autoscaler
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-question-generator-ai-worker
    target:
      kind: HorizontalPodAutoscaler
      name: celery-question-generator-ai-worker-autoscaler

  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: examxv2-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/29c7b407-7f44-4060-ab94-602a60d331a5
          alb.ingress.kubernetes.io/auth-tls-verify-client: "optional"
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://examx.ai,https://www.examx.ai,https://*.examx.ai
          alb.ingress.kubernetes.io/load-balancer-attributes: >-
            idle_timeout.timeout_seconds=60,
            deletion_protection.enabled=true,
            routing.http2.enabled=true,
            routing.http.drop_invalid_header_fields.enabled=true,
            access_logs.s3.enabled=true,
            access_logs.s3.bucket=examx-v2-production-logs,
            access_logs.s3.prefix=ELBLogs/Backend
      spec:
        tls:
          - hosts:
              - examx.ai
            secretName: tls-secret
    target:
      kind: Ingress
      name: examxv2-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-prod-nmQjmP
              objectAlias: ".env"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-backend-secrets

  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-google-credentials
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-backend-googlecredentials-prod-lc6rvm
              objectAlias: "google-credentials.json"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-google-credentials

  # # Redis Autoscaler patches
  # - patch: |-
  #     apiVersion: autoscaling/v2
  #     kind: HorizontalPodAutoscaler
  #     metadata:
  #       name: redis-pod-autoscaler
  #     spec:
  #       minReplicas: 1
  #       maxReplicas: 5
  #   target:
  #     kind: HorizontalPodAutoscaler
  #     name: redis-pod-autoscaler
