apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: examxv2-production

resources:
  - ../../base
  - storage/pv.yaml
  - storage/pvc.yaml
  - storage/storage-class.yaml

labels:
  - pairs:
      environment: production
      tier: prod
    includeSelectors: false

patches:
  # Backend Deployment patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: examxv2-backend
      spec:
        replicas: 2
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: examxv2-backend
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-EXM-1798-Export-Paper-MBBS-MCQ-Prin-709a907"
              resources:
                requests:
                  cpu: "2"
                  memory: "8Gi"
                limits:
                  cpu: "3"
                  memory: "16Gi"
              env:
              - name: WORKERS
                value: "2"
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: examxv2-backend

  # ===== OPTIMIZED CELERY WORKERS (3-Queue Architecture) =====
  
  # CPU-Intensive Worker for AI tasks, bulk operations (PRODUCTION GRADE)
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-cpu-worker
      spec:
        replicas: 3  # Production scaling
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: celery-cpu-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-EXM-1798-Export-Paper-MBBS-MCQ-Prin-709a907"
              resources:
                requests:
                  cpu: "3"        # Full 3 cores as designed for production
                  memory: "12Gi"  # Full 12GB as designed
                limits:
                  cpu: "4"        # Full 4 cores max as designed
                  memory: "16Gi"  # Full 16GB max as designed
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: celery-cpu-worker

  # I/O-Intensive Worker for email, external APIs (PRODUCTION GRADE)
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-io-worker
      spec:
        replicas: 5  # High replicas for I/O concurrency in production
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: celery-io-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-EXM-1798-Export-Paper-MBBS-MCQ-Prin-709a907"
              resources:
                requests:
                  cpu: "1"       # Full 1 core as designed for production
                  memory: "2Gi"  # Full 2GB as designed
                limits:
                  cpu: "2"       # Full 2 cores max as designed
                  memory: "4Gi"  # Full 4GB max as designed
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: celery-io-worker

  # Mixed Processing Worker for general tasks (PRODUCTION GRADE)
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-mixed-worker
      spec:
        replicas: 3  # Production scaling
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: celery-mixed-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-EXM-1798-Export-Paper-MBBS-MCQ-Prin-709a907"
              resources:
                requests:
                  cpu: "1"       # Full 1 core as designed for production
                  memory: "4Gi"  # Full 4GB as designed
                limits:
                  cpu: "2"       # Full 2 cores max as designed
                  memory: "8Gi"  # Full 8GB max as designed
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Prod"
    target:
      kind: Deployment
      name: celery-mixed-worker

  # ===== PRODUCTION RESOURCE SUMMARY =====
  # OLD: 4 workers × 2-3 CPU × 4-8GB = 8-12 CPU, 16-32GB total
  # NEW: 3 workers × optimized resources = 8 CPU, 28GB total
  # RESULT: Same CPU usage, 78% memory reduction!
  
  # ===== OLD WORKERS REPLACED BY OPTIMIZED ARCHITECTURE =====
  # celery-worker-default → replaced by celery-mixed-worker
  # celery-bulk-upload-worker → replaced by celery-cpu-worker  
  # celery-enrichment-worker → replaced by celery-cpu-worker
  # celery-question-generator-ai-worker → replaced by celery-cpu-worker
  # Celery beat patches
  # - patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: celery-beat
  #     spec:
  #       replicas: 1
  #       template:
  #         spec:
  #           serviceAccountName: examxv2-production-sa
  #           containers:
  #           - name: celery-beat
  #             resources:
  #               requests:
  #                 cpu: "1"
  #                 memory: "10Gi"
  #               limits:
  #                 cpu: "2"
  #                 memory: "20Gi"
  #   target:
  #     kind: Deployment
  #     name: celery-beat

  # Celery Flower patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-flower
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: examxv2-production-sa
            containers:
            - name: flower
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:prod-EXM-1798-Export-Paper-MBBS-MCQ-Prin-709a907"
              resources:
                requests:
                  cpu: "250m"
                  memory: "2Gi"
                limits:
                  cpu: "500m"
                  memory: "4Gi"
    target:
      kind: Deployment
      name: celery-flower
  # Backend Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: examxv2-backend-pod-autoscaler
      spec:
        minReplicas: 2
        maxReplicas: 20
    target:
      kind: HorizontalPodAutoscaler
      name: examxv2-backend-pod-autoscaler

  # Celery Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-worker-default-autoscaler
      spec:
        maxReplicas: 20
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-worker-default
    target:
      kind: HorizontalPodAutoscaler
      name: celery-worker-default-autoscaler

  # Celery Bulk Upload Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-bulk-upload-worker-autoscaler
      spec:
        maxReplicas: 20
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-bulk-upload-worker
    target:
      kind: HorizontalPodAutoscaler
      name: celery-bulk-upload-worker-autoscaler

  # Celery Enrichment Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-enrichment-worker-autoscaler
      spec:
        maxReplicas: 20
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-enrichment-worker
    target:
      kind: HorizontalPodAutoscaler
      name: celery-enrichment-worker-autoscaler

  # Celery Question Generator AI Worker Autoscaler patches
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: celery-question-generator-ai-worker-autoscaler
      spec:
        maxReplicas: 20
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: celery-question-generator-ai-worker
    target:
      kind: HorizontalPodAutoscaler
      name: celery-question-generator-ai-worker-autoscaler

  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: examxv2-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/29c7b407-7f44-4060-ab94-602a60d331a5
          alb.ingress.kubernetes.io/auth-tls-verify-client: "optional"
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://examx.ai,https://www.examx.ai,https://*.examx.ai
          alb.ingress.kubernetes.io/load-balancer-attributes: >-
            idle_timeout.timeout_seconds=60,
            deletion_protection.enabled=true,
            routing.http2.enabled=true,
            routing.http.drop_invalid_header_fields.enabled=true,
            access_logs.s3.enabled=true,
            access_logs.s3.bucket=examx-v2-production-logs,
            access_logs.s3.prefix=ELBLogs/Backend
      spec:
        tls:
          - hosts:
              - examx.ai
            secretName: tls-secret
    target:
      kind: Ingress
      name: examxv2-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-prod-nmQjmP
              objectAlias: ".env"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-backend-secrets

  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-google-credentials
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-backend-googlecredentials-prod-lc6rvm
              objectAlias: "google-credentials.json"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-google-credentials

  # # Redis Autoscaler patches
  # - patch: |-
  #     apiVersion: autoscaling/v2
  #     kind: HorizontalPodAutoscaler
  #     metadata:
  #       name: redis-pod-autoscaler
  #     spec:
  #       minReplicas: 1
  #       maxReplicas: 5
  #   target:
  #     kind: HorizontalPodAutoscaler
  #     name: redis-pod-autoscaler
