apiVersion: v1
kind: Service
metadata:
  name: celery-flower-service
  labels:
    app: celery-flower
spec:
  selector:
    app: celery-flower
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
      name: http
  type: ClusterIP 