apiVersion: v1
kind: Service
metadata:
  name: examxv2-backend-service
spec:
  selector:
    app: examxv2-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: 443
  type: ClusterIP
