apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-examxv2-backend-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-010d3510b6aaa1d1f