apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-io-worker
  labels:
    app: celery-io-worker
spec:
  replicas: 1 # Default value, will be overridden in overlays
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 # Ensures zero downtime
  selector:
    matchLabels:
      app: celery-io-worker
  template:
    metadata:
      labels:
        app: celery-io-worker
    spec:
      serviceAccountName: examxv2-sa # Placeholder, to be overridden
      terminationGracePeriodSeconds: 30
      volumes:
        - name: examxv2-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "examxv2-backend-secrets"
        - name: examxv2-google-credentials
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: examxv2-google-credentials
        - name: examxv2-backend-storage
          persistentVolumeClaim:
            claimName: examxv2-backend-pvc
      containers:
        - name: celery-io-worker
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:stg-20250814-132223-859cae893d229663024ed2546db378875707496e
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"      # Much more efficient for I/O
              memory: "2Gi" # Massive memory reduction (87% less)
            limits:
              cpu: "2"      
              memory: "4Gi" # Still 87% reduction vs current
          env:
            - name: CELERY_WORKER_POOL
              value: "gevent"
            - name: CELERY_WORKER_CONCURRENCY
              value: "200"
            - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
              value: "1000"
            - name: GEVENT_RESOLVER
              value: "ares"
          command:
            - celery
            - -A
            - examx  
            - worker
            - --pool=gevent
            - --concurrency=200
            - --queues=io_intensive
            - --hostname=io-worker@%h
            - --max-tasks-per-child=1000
            - -l
            - info
            - -E
          volumeMounts:
            - name: examxv2-secrets-volume
              mountPath: /mnt/secret-store
              readOnly: true
            - name: examxv2-backend-storage
              mountPath: /app/media
            - name: examxv2-google-credentials
              mountPath: /app/google-credentials.json
              subPath: google-credentials.json
          lifecycle:
            postStart:
              exec:
                command: ['cp', '-R', '/mnt/secret-store/.env', '/app/examx/.env']
