apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1 # Default value, will be overridden in overlays
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 # Ensures zero downtime by not allowing any unavailable pods
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      serviceAccountName: examxv2-sa # Placeholder, to be overridden
      terminationGracePeriodSeconds: 30
      volumes:
        - name: examxv2-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "examxv2-backend-secrets"
        - name: examxv2-backend-storage
          persistentVolumeClaim:
            claimName: examxv2-backend-pvc
      containers:
        - name: celery-worker
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:EXM_682___QP_Code__QP_code_sho-20250606-070725-f006e03
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"
              memory: "16Gi"
            limits:
              cpu: "2"
              memory: "32Gi"
          # env:
          #   - name: REDIS_URL
          #     value: redis://redis-service:6379
          command:
            - celery
            - -A
            - examx
            - worker
            - -l
            - debug
            - -E
          volumeMounts:
            - name: examxv2-secrets-volume
              mountPath: /mnt/secret-store
              readOnly: true
            - name: examxv2-backend-storage
              mountPath: /app/media
          lifecycle:
            postStart:
              exec:
                command: ['cp', '-R', '/mnt/secret-store/.env', '/app/examx/.env']
