apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-default-scaler
  labels:
    app: celery-worker-default
spec:
  scaleTargetRef:
    name: celery-worker-default
  pollingInterval: 15  
  cooldownPeriod: 60  
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: redis
      metadata:
        address: "master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
        listName: "default"  
        listLength: "1"
        enableTLS: "true"
        unsafeSsl: "true"
    # - type: cpu
    #   metadata:
    #     type: Utilization
    #     value: "50"
    # - type: memory
    #   metadata:
    #     type: Utilization
    #     value: "70"