apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-default-scaler
  labels:
    app: celery-worker-default
spec:
  scaleTargetRef:
    name: celery-worker-default
  pollingInterval: 15  
  cooldownPeriod: 60  
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
        metricName: "celery_default_queue_backlog"
        threshold: "1"
        query: |
          sum(examx_celery_queue_pending{queue="default"} + examx_celery_queue_active{queue="default"})
    # - type: cpu
    #   metadata:
    #     type: Utilization
    #     value: "50"
    # - type: memory
    #   metadata:
    #     type: Utilization
    #     value: "70"