apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-examxv2

resources:
  - ../../base
  - storage/pv.yaml
  - storage/pvc.yaml

# Using labels instead of deprecated commonLabels
labels:
  - pairs:
      environment: development
      tier: dev
    includeSelectors: false

# Using patches instead of deprecated patchesStrategicMerge
patches:
  # Backend Deployment patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: examxv2-backend
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: examxv2-backend
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
              env:
              - name: WORKERS
                value: "2"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "priya97"
              - name: OPIK_PROJECT
                value: "Default Project"
    target:
      kind: Deployment
      name: examxv2-backend

  # Celery Worker patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-worker
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "6Gi"
    target:
      kind: Deployment
      name: celery-worker
# Celery beat patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-beat
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-beat
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "6Gi"
    target:
      kind: Deployment
      name: celery-beat
  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: examxv2-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/f191c431-422f-42a6-85ec-13eabec5272f
          alb.ingress.kubernetes.io/auth-tls-verify-client: "optional"
          alb.ingress.kubernetes.io/auth-tls-secret: "dev-examxv2/client-ca-cert"
          alb.ingress.kubernetes.io/custom-response-headers: >-
            SSL-Client-Cert:${tls.client_cert}~
            SSL-Client-Verify:${tls.client_verified}~
            SSL-Client-DN:${tls.client_subject_dn}
      spec:
        tls:
          - hosts:
              - examx.cloud
            secretName: tls-secret
    target:
      kind: Ingress
      name: examxv2-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-secrets-1uLP4S
              objectAlias: ".env"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-backend-secrets
