apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-examxv2

resources:
  - ../../base
  - storage/pv.yaml
  - storage/pvc.yaml

# Using labels instead of deprecated commonLabels
labels:
  - pairs:
      environment: development
      tier: dev
    includeSelectors: false

# Using patches instead of deprecated patchesStrategicMerge
patches:
  # Backend Deployment patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: examxv2-backend
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: examxv2-backend
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:EXM_1454_Implement_the_Time_Ma-20250819-115913-3d62714"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
              env:
              - name: WORKERS
                value: "2"
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: examxv2-backend

  # Celery Worker patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-worker-default
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-worker-default
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:EXM_1454_Implement_the_Time_Ma-20250819-115913-3d62714"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "6Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: celery-worker-default
  # Celery Bulk Upload Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-bulk-upload-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-bulk-upload-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:EXM_1454_Implement_the_Time_Ma-20250819-115913-3d62714"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: celery-bulk-upload-worker

  # Celery Enrichment Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-enrichment-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-enrichment-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:EXM_1454_Implement_the_Time_Ma-20250819-115913-3d62714"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: celery-enrichment-worker

  # Celery Question Generator AI Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-question-generator-ai-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-question-generator-ai-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:EXM_1454_Implement_the_Time_Ma-20250819-115913-3d62714"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: celery-question-generator-ai-worker

  # Celery Flower patches for dev
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-flower
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: flower
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:EXM_1454_Implement_the_Time_Ma-20250819-115913-3d62714"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
    target:
      kind: Deployment
      name: celery-flower

  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: examxv2-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/f191c431-422f-42a6-85ec-13eabec5272f
          alb.ingress.kubernetes.io/auth-tls-verify-client: "optional"
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://examx.cloud,https://www.examx.cloud,https://*.examx.cloud
      spec:
        tls:
          - hosts:
              - examx.cloud
            secretName: tls-secret
    target:
      kind: Ingress
      name: examxv2-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-secrets-1uLP4S
              objectAlias: ".env"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-backend-secrets

  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-google-credentials
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-backend-googlecredentials-dev-zQode4
              objectAlias: "google-credentials.json"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-google-credentials
