apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-examxv2

resources:
  - ../../base
  - storage/pv.yaml
  - storage/pvc.yaml

# Using labels instead of deprecated commonLabels
labels:
  - pairs:
      environment: development
      tier: dev
    includeSelectors: false

# Using patches instead of deprecated patchesStrategicMerge
patches:
  # Backend Deployment patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: examxv2-backend
        annotations:
          kubernetes.io/change-cause: Updated to "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: examxv2-backend
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "1"
              #     memory: "3Gi"
              #   limits:
              #     cpu: "2"
              #     memory: "6Gi"
              env:
              - name: WORKERS
                value: "2"
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
              - name: REDIS_URL
                value: "redis://master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
    target:
      kind: Deployment
      name: examxv2-backend

  # Celery Worker patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-worker-default
        annotations:
          kubernetes.io/change-cause: Updated to "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-worker-default
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "200m"
              #     memory: "2Gi"
              #   limits:
              #     cpu: "400m"
              #     memory: "3Gi"
              command:
              - celery
              - -A
              - examx
              - worker
              - -P
              - gevent
              - -c
              - "25"
              - -Q
              - default
              - -l
              - info
              - -E
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
              - name: REDIS_URL
                value: "redis://master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
    target:
      kind: Deployment
      name: celery-worker-default
  # Celery Bulk Upload Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-bulk-upload-worker
        annotations:
          kubernetes.io/change-cause: Updated to "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-bulk-upload-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "300m"
              #     memory: "2Gi"
              #   limits:
              #     cpu: "400m"
              #     memory: "3Gi"
              command:
              - celery
              - -A
              - examx
              - worker
              - -P
              - prefork
              - -c
              - "1"
              - -Q
              - bulk_upload
              - -l
              - info
              - -E
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME 
                value: "Dev"
              - name: REDIS_URL
                value: "redis://master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
    target:
      kind: Deployment
      name: celery-bulk-upload-worker

  # Celery Enrichment Worker patches - disabled in dev
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-enrichment-worker
      spec:
        replicas: 0
        template:
          spec:
            containers:
            - name: celery-enrichment-worker
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "300m"
              #     memory: "2Gi"
              #   limits:
              #     cpu: "500m"
              #     memory: "3Gi"
    target:
      kind: Deployment
      name: celery-enrichment-worker

  # Celery Question Generator AI Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-question-generator-ai-worker
        annotations:
          kubernetes.io/change-cause: Updated to "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-question-generator-ai-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "200m"
              #     memory: "2Gi"
              #   limits:
              #     cpu: "400m"
              #     memory: "3Gi"
              command:
              - celery
              - -A
              - examx
              - worker
              - -P
              - gevent
              - -c
              - "25"
              - -Q
              - question_generator_ai
              - -l
              - info
              - -E
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
              - name: REDIS_URL
                value: "redis://master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
    target:
      kind: Deployment
      name: celery-question-generator-ai-worker

  # Celery Flower patches for dev
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-flower
        annotations:
          kubernetes.io/change-cause: Updated to "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: flower
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-Revert-Refactor-Celery-Prometheus-e-e1f5bf0be60cf6def55a4bb58d2ef3483232618d"
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "200m"
              #     memory: "1Gi"
              #   limits:
              #     cpu: "400m"
              #     memory: "2Gi"
    target:
      kind: Deployment
      name: celery-flower

  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: examxv2-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/f191c431-422f-42a6-85ec-13eabec5272f
          alb.ingress.kubernetes.io/auth-tls-verify-client: "optional"
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://examx.cloud,https://www.examx.cloud,https://*.examx.cloud
      spec:
        tls:
          - hosts:
              - examx.cloud
            secretName: tls-secret
    target:
      kind: Ingress
      name: examxv2-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-secrets-1uLP4S
              objectAlias: ".env"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-backend-secrets

  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-google-credentials
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-backend-googlecredentials-dev-zQode4
              objectAlias: "google-credentials.json"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-google-credentials

  # Disable celery-enrichment-worker-autoscaler in dev
  # - patch: |-
  #     apiVersion: autoscaling/v2
  #     kind: HorizontalPodAutoscaler
  #     metadata:
  #       name: celery-enrichment-worker-autoscaler
  #     spec:
  #       minReplicas: 0
  #       maxReplicas: 1
  #       scaleTargetRef:
  #         apiVersion: apps/v1
  #         kind: Deployment
  #         name: celery-enrichment-worker
  #   target:
  #     kind: HorizontalPodAutoscaler
  #     name: celery-enrichment-worker-autoscaler

  # KEDA ScaledObject patches for dev environment
  - patch: |-
      apiVersion: keda.sh/v1alpha1
      kind: ScaledObject
      metadata:
        name: celery-worker-default-scaler
      spec:
        minReplicaCount: 1
        maxReplicaCount: 3 
        cooldownPeriod: 30
        triggers:
        - type: redis
          metadata:
            address: "master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
            listName: "default"
            listLength: "1"  
            enableTLS: "true"
            unsafeSsl: "true"
    target:
      kind: ScaledObject
      name: celery-worker-default-scaler

  - patch: |-
      apiVersion: keda.sh/v1alpha1
      kind: ScaledObject
      metadata:
        name: celery-bulk-upload-worker-scaler
      spec:
        minReplicaCount: 1
        maxReplicaCount: 2 
        cooldownPeriod: 30
        triggers:
        - type: redis
          metadata:
            address: "master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
            listName: "bulk_upload"
            listLength: "1"  
            enableTLS: "true"
            unsafeSsl: "true"
    target:
      kind: ScaledObject
      name: celery-bulk-upload-worker-scaler

  - patch: |-
      apiVersion: keda.sh/v1alpha1
      kind: ScaledObject
      metadata:
        name: celery-enrichment-worker-scaler
      spec:
        minReplicaCount: 0  
        maxReplicaCount: 3 
        cooldownPeriod: 30
        triggers:
        - type: redis
          metadata:
            address: "master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
            listName: "question_enrichment"
            listLength: "1"  
            enableTLS: "true"
            unsafeSsl: "true"
    target:
      kind: ScaledObject
      name: celery-enrichment-worker-scaler

  - patch: |-
      apiVersion: keda.sh/v1alpha1
      kind: ScaledObject
      metadata:
        name: celery-question-generator-ai-worker-scaler
      spec:
        minReplicaCount: 1 
        maxReplicaCount: 2 
        cooldownPeriod: 30
        triggers:
        - type: redis
          metadata:
            address: "master.examxv2-dev.kti2un.aps1.cache.amazonaws.com:6379"
            listName: "question_generator_ai"
            listLength: "1"  
            enableTLS: "true"
            unsafeSsl: "true"
    target:
      kind: ScaledObject
      name: celery-question-generator-ai-worker-scaler

