apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-examxv2

resources:
  - ../../base
  - storage/pv.yaml
  - storage/pvc.yaml

# Using labels instead of deprecated commonLabels
labels:
  - pairs:
      environment: development
      tier: dev
    includeSelectors: false

# Using patches instead of deprecated patchesStrategicMerge
patches:
  # Backend Deployment patches - only mutable fields
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: examxv2-backend
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: examxv2-backend
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-EXM-1825-Authoring-Screen-Section-B-13b6bfe9c9b0504d905f8a1832bd73ff3ede2d34"
              resources:
                requests:
                  cpu: "500m"
                  memory: "3Gi"
                limits:
                  cpu: "1"
                  memory: "6Gi"
              env:
              - name: WORKERS
                value: "2"
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: examxv2-backend

  # ===== OPTIMIZED CELERY WORKERS (3-Queue Architecture) =====
  
  # CPU-Intensive Worker for AI tasks, bulk operations
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-cpu-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-cpu-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-EXM-1825-Authoring-Screen-Section-B-13b6bfe9c9b0504d905f8a1832bd73ff3ede2d34"
              resources:
                requests:
                  cpu: "1500m"  # 1.5 cores for dev (scaled down from prod)
                  memory: "6Gi"  # 6GB for dev (scaled down from prod)
                limits:
                  cpu: "2"      # 2 cores max for dev
                  memory: "8Gi" # 8GB max for dev
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: celery-cpu-worker

  # I/O-Intensive Worker for email, external APIs
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-io-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-io-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-EXM-1825-Authoring-Screen-Section-B-13b6bfe9c9b0504d905f8a1832bd73ff3ede2d34"
              resources:
                requests:
                  cpu: "500m"   # 0.5 cores for dev
                  memory: "1Gi" # 1GB for dev (scaled down from prod)
                limits:
                  cpu: "1"      # 1 core max for dev
                  memory: "2Gi" # 2GB max for dev
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: celery-io-worker

  # Mixed Processing Worker for general tasks
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-mixed-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: celery-mixed-worker
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-EXM-1825-Authoring-Screen-Section-B-13b6bfe9c9b0504d905f8a1832bd73ff3ede2d34"
              resources:
                requests:
                  cpu: "500m"   # 0.5 cores for dev
                  memory: "2Gi" # 2GB for dev (scaled down from prod)
                limits:
                  cpu: "1"      # 1 core max for dev
                  memory: "4Gi" # 4GB max for dev
              env:
              - name: OPIK_URL_OVERRIDE
                value: "https://www.comet.com/opik/api"
              - name: OPIK_API_KEY
                value: "Y5T3WoqNxJ22ypw1M8qivydis"
              - name: OPIK_WORKSPACE
                value: "greatify-prod"
              - name: OPIK_PROJECT_NAME
                value: "Dev"
    target:
      kind: Deployment
      name: celery-mixed-worker

  # ===== OLD WORKERS REPLACED BY OPTIMIZED ARCHITECTURE =====
  # celery-worker-default → replaced by celery-mixed-worker
  # celery-bulk-upload-worker → replaced by celery-cpu-worker  
  # celery-enrichment-worker → replaced by celery-cpu-worker
  # celery-question-generator-ai-worker → replaced by celery-cpu-worker

  # Celery Flower patches for dev
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: celery-flower
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: dev-examxv2-sa
            containers:
            - name: flower
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:dev-EXM-1825-Authoring-Screen-Section-B-13b6bfe9c9b0504d905f8a1832bd73ff3ede2d34"
              resources:
                requests:
                  cpu: "200m"
                  memory: "1Gi"
                limits:
                  cpu: "400m"
                  memory: "2Gi"
    target:
      kind: Deployment
      name: celery-flower

  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: examxv2-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/f191c431-422f-42a6-85ec-13eabec5272f
          alb.ingress.kubernetes.io/auth-tls-verify-client: "optional"
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://examx.cloud,https://www.examx.cloud,https://*.examx.cloud
      spec:
        tls:
          - hosts:
              - examx.cloud
            secretName: tls-secret
    target:
      kind: Ingress
      name: examxv2-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-secrets-1uLP4S
              objectAlias: ".env"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-backend-secrets

  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: examxv2-google-credentials
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:examxv2-backend-googlecredentials-dev-zQode4
              objectAlias: "google-credentials.json"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: examxv2-google-credentials
