apiVersion: v1
kind: PersistentVolume
metadata:
  name: uat-examxv2-backend-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04d0c6726e9461486
