apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-cpu-worker-hpa
  labels:
    app: celery-cpu-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-cpu-worker
  minReplicas: 1
  maxReplicas: 3  # Limited replicas for CPU-intensive tasks
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when CPU > 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when memory > 80%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120  # 2 minutes - faster for bulk upload spikes
      policies:
      - type: Pods
        value: 2           # Scale up 2 pods for CPU-intensive bursts
        periodSeconds: 120 # Check every 2 minutes
      - type: Percent
        value: 50          # 50% increase for major spikes
        periodSeconds: 180 # Alternative method after 3 minutes
    scaleDown:
      stabilizationWindowSeconds: 1200 # 20 minutes - CPU tasks take longer to complete
      policies:
      - type: Pods
        value: 1           # Conservative scale down for CPU workers
        periodSeconds: 900 # Scale down 1 pod every 15 minutes
