apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-cpu-worker-hpa
  labels:
    app: celery-cpu-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-cpu-worker
  minReplicas: 1
  maxReplicas: 3  # Limited replicas for CPU-intensive tasks
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when CPU > 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when memory > 80%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300  # 5 minutes before scaling up
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes before scaling down
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600
