apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-mixed-worker-hpa
  labels:
    app: celery-mixed-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-mixed-worker
  minReplicas: 1
  maxReplicas: 2  # Moderate scaling for mixed workloads
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Moderate CPU threshold
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75  # Scale when memory > 75%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 240  # 4 minutes 
      policies:
      - type: Pods
        value: 1
        periodSeconds: 240
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes before scaling down
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600
